### ISSUE TITLE
Add parameter to change camera id

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/vision#2]
https://github.com/SouthEugeneRoboticsTeam/vision/blob/master/vision/app.py#L71

We just need to accept an input for the camera id (maybe `-c`/`--camera`) and change

```python
camera = cv2.VideoCapture(0)
```

to something like

```python
camera = cv2.VideoCapture(camera)
```

**Comment by andrewda** [comment]
Completed in eda390514e4744a7bc7c888a3d9d586dea60fb4c

**Comment by SUPERCILEX** [comment]
@andrewda tip of the day: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by andrewda** [comment]
@SUPERCILEX Yup ;) Forgot this issue was even open so didn't add it to the commit message lol
